on: [push, pull_request]

name: Linux Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        arch: ["x86_64", "i686"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: facebookresearch/fastText
          ref: v0.9.2
          path: fastText
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Build manylinux wheels
        run: |
            docker run --rm -v `pwd`:/io -w /io quay.io/pypa/manylinux2010_${{ matrix.arch }} sh manylinux.sh
            ls -lrth dist/
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: linux-wheels
          path: dist/fasttext_wheel-*.whl
      - name: Publish manylinux package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          skip_existing: true

  cross-build:
    name: Cross Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "armv7l"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: facebookresearch/fastText
          ref: v0.9.2
          path: fastText
      - name: Build manylinux wheels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Login without echoing token, just in case
          BASH_FLAGS="$-"
          set +x
          echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com \
            -u "$GITHUB_ACTOR" \
            --password-stdin
          set "$BASH_FLAGS"
          docker run -e ARCH=${{ matrix.arch }} --rm -v `pwd`:/io -w /io docker.pkg.github.com/messense/manylinux2014-cross-arm/manylinux2014-cross:${{ matrix.arch }} sh manylinux-cross.sh
          ls -lrth dist/
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: linux-wheels
          path: dist/fasttext_wheel-*.whl
      - name: Publish manylinux package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          skip_existing: true
